---
kind: pipeline
type: docker
name: push

platform:
  os: linux
  arch: amd64

steps:
- name: build
  image: plugins/docker
  settings:
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
    repo: robbymilo/go-meta-image-generator
    tags: latest
  when:
    branch:
      include:
        - main

trigger:
  event:
  - push

